services:

  app-python:
    container_name: app-python
    image: prgs/python:app
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - 3002:3002

  postgres:
    image: postgres:17-alpine
    user: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - metrics      
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: grafana, books    
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./postgresql/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh      
    command: |
      postgres
      -c wal_level=logical
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 3s
      timeout: 6s
      retries: 10

networks:
  metrics:
    driver: bridge
