kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: default
data:
  auto_conf.yaml: |-
    ad_identifiers:
      - kube_scheduler
    init_config:
    instances:
      - prometheus_url: http://%%host%%:10251/metrics
        leader_election: false