x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

services:

  loki:
    container_name: loki
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - metrics
    ports:
      - 3100:3100

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    networks:
      - metrics
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - loki
    logging: *default-logging

  app-python:
    container_name: app-python
    image: prgs/python:app
    restart: unless-stopped
    networks:
      - metrics
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
    ports:
      - 3002:3002
    environment:
      APP_NAME: "app-books"
    depends_on:
      - loki
    logging: *default-logging  

  prometheus:
    image: prom/prometheus
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - ./data/monitoring/prometheus/config:/etc/prometheus
      - ./data/monitoring/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'      
    ports:
      - 9090:9090
    networks:
      - metrics
    depends_on:
      - app-python
      - loki
    logging: *default-logging     

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - ./data/monitoring/alertmanager/config:/etc/alertmanager
      - ./data/monitoring/alertmanager/data:/alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global
    networks:
      - metrics
    logging: *default-logging

  app-prometheusbot:
    container_name: app-prometheusbot
    image: prgs/telegrambot:app
    restart: unless-stopped
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - ./data/monitoring/alertmanager/telegrambot/config.yaml:/config.yaml
    networks:
      - metrics
    logging: *default-logging  

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    environment:
      TZ: America/Sao_Paulo    
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8585:8080
    networks:
      - metrics
    restart: unless-stopped
    logging: *default-logging

  postgres:
    image: postgres:17-alpine
    user: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - metrics      
    environment:
      POSTGRES_USER: grafana
      POSTGRES_DB: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - ./data/postgresql/pgdata:/var/lib/postgresql/data      
    command: |
      postgres
      -c wal_level=logical
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "grafana"]
      interval: 3s
      timeout: 6s
      retries: 10
    logging: *default-logging

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://grafana:grafana@postgres:5432/?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/queries/queries.yaml"
    networks:
      - metrics
    volumes:
      - ./data/monitoring/prometheus/custom-queries:/queries
      - ./data/monitoring/timezone/localtime:/etc/localtime
    depends_on:
      - postgres
    logging: *default-logging   

  grafana:
    image: grafana/grafana:latest
    container_name: grafana    
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana
      GF_DATABASE_SSL_MODE: disable
    restart: unless-stopped
    networks:
      - metrics    
    depends_on:
      - postgres
      - loki 
    ports:
      - 3000:3000
    volumes:
      - ./data/monitoring/timezone/localtime:/etc/localtime
      - ./data/monitoring/grafana/data:/var/lib/grafana
      - ./data/monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    logging: *default-logging

networks:
  metrics:
    driver: bridge
