services:

  app-node:
    container_name: app-node
    image: prgs/node:app
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - 3001:3001

networks:
  metrics:
    driver: bridge
