services:

  app-prometheusbot:
    container_name: app-prometheusbot
    image: prgs/telegrambot:app
    restart: unless-stopped
    volumes:
      - ./telegrambot/config.yaml:/config.yaml
    networks:
      - metrics
    ports:
      - 9087:9087

networks:
  metrics:
    driver: bridge
