services:

  postgres:
    image: postgres:17-alpine
    user: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - metrics      
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: books, grafana
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  books:
    container_name: books
    image: prgs/backend-books:app
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - 3002:3002
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: prgs/frontend-books:app
    restart: unless-stopped
    networks:
      - metrics
    ports:
      - 3003:3003

networks:
  metrics:
    driver: bridge
