apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
      annotations:
        ad.datadoghq.com/service-a.logs: '[{"source":"python","service":"service-a"}]'
    spec:
      containers:
      - name: service-a
        image: gcr.io/{{PROJECT_ID}}/service-a:1.0.0
        ports:
          - containerPort: 8001
            protocol: TCP
        env:
          - name: SERVICE_HOST
            value: "service-b"
          - name: SERVICE_PORT
            value: "8002"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_ENV
            value: "production"
          - name: DD_SERVICE
            value: "service-a"
          - name: DATADOG_TRACE_ENABLED
            value: "true"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_TRACE_ANALYTICS_ENABLED
            value: "true"
        readinessProbe:
          httpGet:
            port: 8001
            path: /
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            port: 8001
            path: /
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 4
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
